server:
  port: 8888

mybatis:
  type-aliases-package: cn.edu.hqu.cst.api.entity
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db_api?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: root
    password: 1234
